In [38]:
import numpy as np
from m6bk import compute_plane, compute_plane2
np.random.seed(1)

def data(N=10000, a=1, b=2, c=1, d=3):
    '''Generate N number of 3D points 
    around the plane ax + by + cz + d = 0
    '''
    x = np.random.rand(N)
    y = np.random.rand(N)
    noise = np.random.normal(0, 0.1, size=x.shape)
    
    # ax + by + cz + d = 0
    # cz = -d - a*x - b*y + noise

    z = (1.0/c) * (-d -a*x - b*y + noise)
    points = np.vstack((x, y, z))
    return points
    
# data around the plane: x + 2y + z + 3 = 0
points = data(N=100000)
print(f"points.shape: {points.shape}, \n {np.round(points[:, 0:5], 2)}")

points.shape: (3, 100000), 
 [[ 0.42  0.72  0.    0.3   0.15]
 [ 0.32  0.6   0.13  0.34  0.74]
 [-3.99 -4.9  -3.15 -3.88 -4.62]]


In [39]:
a,b, c, d = compute_plane(points)

normalize_factor = 1.0/a
a = normalize_factor * a
b = normalize_factor * b
c = normalize_factor * c
d = normalize_factor * d

print(f"Plane Equation: {a:.3f}x + {b:.3f}y + {c:.3f}z + {d:.3f} = 0")

Plane Equation: 1.000x + 2.002y + 0.981z + 2.913 = 0


In [40]:
a,b, c, d = compute_plane2(points)

normalize_factor = 1.0/a
a = normalize_factor * a
b = normalize_factor * b
c = normalize_factor * c
d = normalize_factor * d

print(f"Plane Equation: {a:.3f}x + {b:.3f}y + {c:.3f}z + {d:.3f} = 0")

MemoryError: Unable to allocate 74.5 GiB for an array with shape (100000, 100000) and data type float64

In [ ]:
# using least square
def fit_plane(points):
    x = points[0, :]
    y = points[1, :]
    z = points[2, :]

    # ax + by + cz + d = 0
    # a*x + b*y + d = -cz
    # constraint c = 1 through scaling normalization
    # Column stack A = [X, Y, 1], B = -Z
    # Solve for x s.t. Ax = B using least square
    # where x = [a, b, d]

    A = np.column_stack((x, y, np.ones(len(x))))
    B = -z
    c = 1
    
    a, b, d = np.linalg.lstsq(A, B, rcond=None)[0]
    return a, b, c, d 

a, b, c, d = fit_plane(points)

normalize_factor = 1.0/a
a = normalize_factor * a
b = normalize_factor * b
c = normalize_factor * c
d = normalize_factor * d

print(f"plane equation: {a:.3f}x + {b:.3f}y + {c:.3f}z + {d:.3f} = 0")

plane equation: 1.000x + 2.011y + 1.006z + 3.020 = 0
