<img src="quiz.png" width=800>

In [ ]:
import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt
from matplotlib import patches

%matplotlib inline
%load_ext autoreload
%autoreload 2
%precision %.2f

import files_management

t = np.reshape(np.array([1, 2, 10]), [3, 1])
R = -1* np.identity(3)
R[0, 0] = 1
print(F"R:\n {R}")

T = np.hstack([R, t])
print(F"T:\n {T}")

o_world = np.reshape(np.array([-.5, 1.5, 9]), [3, 1])
o_world = np.vstack([o_world, 1])

o_cam = np.dot(T, o_world)

print(F"position of this point in the camera coordinate system: \n {o_cam}")

K = np.array([ [640, 0, 640], [0, 480, 480], [0, 0, 1] ])
print(F"K: \n {K}")

print(F"pixel location of the 2D projection of the point O on the image plane: \n {np.dot(K, o_cam)}")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
R:
 [[ 1. -0. -0.]
 [-0. -1. -0.]
 [-0. -0. -1.]]
T:
 [[ 1. -0. -0.  1.]
 [-0. -1. -0.  2.]
 [-0. -0. -1. 10.]]
position of this point in the camera coordinate system: 
 [[0.5]
 [0.5]
 [1. ]]
K: 
 [[640   0 640]
 [  0 480 480]
 [  0   0   1]]
pixel location of the 2D projection of the point O on the image plane: 
 [[960.]
 [720.]
 [  1.]]
